#!/bin/sh
#
# Gradle start up script for POSIX generated by "Gradle"
#
# Licensed under the Apache License, Version 2.0

##############################################################################
# Helper functions
##############################################################################

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

log () {
    if ! "$app_verbose" 2>/dev/null; then
        return 0
    fi
    echo "$1"
} >&2

##############################################################################
# Determine the Java command to use to start the JVM.
##############################################################################

if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD="java"
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

##############################################################################
# Increase the maximum file descriptors if we can.
##############################################################################

if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        MAX_FD=$( ulimit -H -n ) ||
            log "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        ulimit -n "$MAX_FD" ||
            log "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

##############################################################################
# Collect all arguments for the java command
##############################################################################

set -- \
    "-Dorg.gradle.appname=$APP_BASE_NAME" \
    -classpath "$CLASSPATH" \
    org.gradle.wrapper.GradleWrapperMain \
    "$@"

##############################################################################
# Determine the APP_HOME directory
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${0%"${0##*/}"}" && pwd -P ) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

exec "$JAVACMD" "$@"
